### ISSUE TITLE
How to use rspack.config.js configuration?

### ISSUE THREAD

**Issue by tomocrafter** [rspack-contrib/storybook-rsbuild#60]
Since rspack is designed with compatibility with webpack in mind, migrating from webpack to rspack seems natural. However, in Storybook, the config is read using webpack, whereas for Storybook compatibility with rspack, rsbuild is used instead. Therefore, it seems necessary to convert rspack config further to rsbuild. Is it possible to use rspack configuration directly with storybook-rsbuild?

**Comment by fi3ework** [comment]
For short, the answer is NO.

Rsbuild is based on Rspack, with out-of-box and lots of optimal configurations. So it's a superset of Rspack.

The configuration of webpack can be very diverse. If you are willing to try, you can create a new `rsbuild.config.ts` and configure it like this. This is not guaranteed to work 100% completely, because I am not sure whether your webpack config will not conflict with Rsbuild at all (such as dev server configuration, etc).

```js
import { defineConfig } from '@rsbuild/core';

export default defineConfig({
  tools: {
    rspack: {
      // your webpack/rspack config here.
    }
  }
});
```

**Comment by fi3ework** [comment]
Closing as this may not off the mission of this repository. Maintaining another `storybook-builder-rspack` is possible, but not in the near future. We strongly recommend using Rsbuild in most cases for users.
