### ISSUE TITLE
Can't resolve deps with @rsbuild/core 1.0.1-beta.10

### ISSUE THREAD

**Issue by opsidao** [rspack-contrib/storybook-rsbuild#61]
When I try to add the dependency to a project that is using the [latest published version](https://www.npmjs.com/package/@rsbuild/core/v/1.0.1-beta.10) of @rsbuild/core I'm getting an errror that it can't resovle the dependency:

```shell
-> % npm add -D storybook-react-rsbuild
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: my-project@1.0.0
npm error Found: @rsbuild/core@1.0.1-beta.10
npm error node_modules/@rsbuild/core
npm error   @rsbuild/core@"^1.0.1-beta.10" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @rsbuild/core@">= 1.0.0-alpha.9" from storybook-react-rsbuild@0.0.10
npm error node_modules/storybook-react-rsbuild
npm error   dev storybook-react-rsbuild@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by fi3ework** [comment]
Well, I think it's because there's a peer dep version check dilemma on NPM. By testing on https://semver.npmjs.com/

<img width="1017" alt="Google Chrome 2024-08-08 00 32 15" src="https://github.com/user-attachments/assets/5a19c98c-63c4-433e-923a-ce6b4f0009d1">

We need to change to

<img width="1170" alt="image" src="https://github.com/user-attachments/assets/9f3f231a-a04a-4b54-a572-fea1c3180624">

I'll fix it soon.
